title: Tomasz Grzebuła | Useful Tech Notes 📚
description: A curated list of free, high-quality resources, courses, and lectures on AI, Machine Learning, and Deep Learning from top universities and some additional resources.
theme: jekyll-theme-cayman
